version: '3.8'
services:
  padq-business-investmentscengenerationtool.backend:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/finance_all?useUnicode=true&characterEncoding=utf8&timeZone=GMT%2B8&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

  padq-business-investmentscengenerationtool.db:
    environment:
      MYSQL_DATABASE: finance_all
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./mysql/config:/etc/mysql/conf.d"
      
  padq-business-investmentscengenerationtool.flask:
    ports:
      - "5000:5000"   

  padq-business-investmentscengenerationtool.nginx:
    ports:
      - 80:9528
      - 81:80
    volumes:
      - ./Service/Business/InvestmentScenGeneration/finance-integration/nginx/finance-integration.conf:/etc/nginx/conf.d/default.conf
      - ./Service/Business/InvestmentScenGeneration/finance-integration/dist/:/usr/share/nginx/html/
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/www/:/usr/share/nginx/sjj/ 

# sjj 部分
  padq-business-investmentscengenerationtool.sjj-backend:

    volumes:
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/python-src/:/usr/src/stock-backend/python-src/
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/algorithm/:/usr/src/stock-backend/algorithm/
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/cron-algorithm/:/usr/src/stock-backend/cron-algorithm/
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/Config.toml:/usr/src/stock-backend/Config.toml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  padq-business-investmentscengenerationtool.sjj-mongodb:
    volumes:
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/db:/data/db

  padq-business-investmentscengenerationtool.sjj-notebook:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 9000:8888
    volumes:
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/:/home/jovyan/work
      - ./Service/Business/InvestmentScenGeneration/stock-backend-raw-main/configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
    environment:
      - JUPYTER_TOKEN=1233ccdb3d1f642dca21b7ed2646df01224d15670aeea220 
volumes:
  mysql_data:
